import test from "node:test";
import assert from "node:assert/strict";
import { getTargetAdapter, listTargetAdapters } from "../packages/targets/src/adapters.js";
import { compileTargetExport } from "../packages/targets/src/exporters.js";
import {
  getSerializer,
  listSerializers,
  serializeRepresentation
} from "../packages/targets/src/serializer-registry.js";
import { exportConfiguration } from "../packages/targets/src/exporter-bridge.js";

const targets = [
  "apple-mobileconfig",
  "apple-dns-declaration",
  "apple-mobileconfig-legacy",
  "surge",
  "mihomo",
  "wireguard",
  "shadowrocket",
  "loon",
  "stash",
  "quantumult-x"
];

const policy = {
  policy: {
    name: "Test",
    dns: true,
    dnsServers: ["1.1.1.1", "1.0.0.1"],
    dnsProfiles: [{
      id: "dns",
      name: "Test DNS",
      protocol: "HTTPS",
      servers: ["1.1.1.1", "1.0.0.1"],
      endpoint: "https://cloudflare-dns.com/dns-query",
      enabled: true
    }],
    rules: [{type: "DOMAIN-SUFFIX", value: "example.com", policy: "DIRECT"}],
    finalPolicy: "DIRECT",
    bypassSystem: true
  }
};

test("all application targets expose a compiler adapter", () => {
  const ids = listTargetAdapters().map(x => x.targetId);
  assert.deepEqual(ids, targets);

  for (const id of targets) {
    const adapter = getTargetAdapter(id);
    assert.equal(adapter.targetId, id);
    assert.equal(typeof adapter.compile, "function");
  }
});

test("each target artifact satisfies its target-specific structural contract", () => {
  const expected = {
    "apple-mobileconfig": [/^<\?xml/, /<plist version="1\.0">/, /com\.apple\.dnsSettings\.managed/],
    "apple-dns-declaration": [/^\{/, /com\.apple\.configuration\.network\.dns-settings/],
    "apple-mobileconfig-legacy": [/^<\?xml/, /<plist version="1\.0">/, /com\.apple\.dnsSettings\.managed/],
    surge: [/\[General\]/, /\[Rule\]/],
    mihomo: [/^dns:/m, /^rules:/m, /MATCH,DIRECT/],
    wireguard: [/^# Generated by Configuration Platform/m, /\[Interface\]/, /\[Peer\]/],
    shadowrocket: [/\[General\]/, /\[Proxy\]/, /\[Rule\]/, /FINAL,DIRECT/],
    loon: [/\[General\]/, /\[Proxy Group\]/, /\[Rule\]/, /FINAL,DIRECT/],
    stash: [/^dns:/m, /^proxy-groups:/m, /^rules:/m, /MATCH,DIRECT/],
    "quantumult-x": [/\[general\]/, /\[dns\]/, /\[filter_local\]/, /final,direct/]
  };

  for (const id of targets) {
    const result = compileTargetExport(id, policy);
    const artifact = String(result.representation);
    assert.ok(artifact.trim().length > 0, id);
    for (const pattern of expected[id]) {
      assert.match(artifact, pattern, `${id}: missing ${pattern}`);
    }
  }
});

test("target exporters preserve explicit DNS input and do not invent a resolver", () => {
  const withoutDns = { policy: { name: "No DNS", rules: [] } };

  for (const id of ["surge", "mihomo", "wireguard", "shadowrocket", "loon", "stash", "quantumult-x"]) {
    const result = compileTargetExport(id, withoutDns);
    const artifact = String(result.representation);
    assert.doesNotMatch(artifact, /1\.1\.1\.1|1\.0\.0\.1/, id);
  }
});

test("all target exporters generate non-empty artifacts", () => {
  for (const id of targets) {
    const result = compileTargetExport(id, policy);
    assert.equal(result.targetId, id);
    assert.equal(typeof result.outputFormat, "string");
    assert.equal(typeof result.filename, "string");
    assert.notEqual(result.representation, null, id);
  }
});

test("legacy Apple MobileConfig target resolves to an actual artifact", () => {
  const result = compileTargetExport("apple-mobileconfig-legacy", policy);
  assert.equal(result.outputFormat, "plist");
  assert.match(result.filename, /\.mobileconfig$/);
  assert.match(result.representation, /com\.apple\.dnsSettings\.managed/);
});

test("serializer registry exposes only the locked output formats", () => {
  assert.deepEqual(listSerializers(), ["text", "ini", "yaml", "json", "plist"]);

  for (const format of listSerializers()) {
    assert.ok(getSerializer(format));
  }

  assert.equal(serializeRepresentation("json", {ok: true}), "{\n  \"ok\": true\n}");
  assert.equal(serializeRepresentation("text", "artifact"), "artifact");
});

test("serializer registry rejects unsupported and duplicate registrations", async () => {
  const { registerSerializer } = await import("../packages/targets/src/serializer-registry.js");

  assert.throws(
    () => registerSerializer("toml", value => String(value)),
    /Unsupported serializer format/
  );

  assert.throws(
    () => registerSerializer("json", value => String(value)),
    /Serializer already registered/
  );
});

test("export bridge blocks failed processing before target compilation", () => {
  const result = exportConfiguration(
    {status: "FAILED", policy: {}},
    {targetId: "surge"}
  );

  assert.equal(result.ok, false);
  assert.equal(result.blocked, true);
  assert.equal(result.artifact, null);
  assert.equal(result.diagnostics[0].code, "PROCESSING_FAILED");
});

test("export bridge compiles and serializes a successful target result", () => {
  const metadata = Object.freeze({
    status: "SUCCEEDED",
    diagnostics: [{code: "INFO", message: "ready"}]
  });

  const result = exportConfiguration(
    {policy: policy.policy, resultMetadata: metadata},
    {targetId: "surge"}
  );

  assert.equal(result.ok, true);
  assert.equal(result.blocked, false);
  assert.equal(result.targetId, "surge");
  assert.equal(result.outputFormat, "ini");
  assert.equal(typeof result.artifact, "string");
  assert.ok(result.artifact.includes("[General]"));
  assert.equal(result.resultMetadata, metadata);
  assert.deepEqual(result.diagnostics, metadata.diagnostics);
});

test("export bridge fails closed on an unknown target", () => {
  const result = exportConfiguration(
    {policy: policy.policy},
    {targetId: "not-registered"}
  );

  assert.equal(result.ok, false);
  assert.equal(result.blocked, true);
  assert.equal(result.artifact, null);
  assert.equal(result.diagnostics[0].code, "TARGET_NOT_REGISTERED");
});

test("export bridge blocks all terminal failure statuses", () => {
  for (const status of ["FAILED", "BLOCKED", "REJECTED"]) {
    const result = exportConfiguration(
      { status, policy: policy.policy },
      { targetId: "surge" }
    );
    assert.equal(result.ok, false, status);
    assert.equal(result.blocked, true, status);
    assert.equal(result.artifact, null, status);
    assert.equal(result.diagnostics[0].code, "PROCESSING_FAILED", status);
  }
});

test("legacy Apple MobileConfig is reachable through the export bridge", () => {
  const result = exportConfiguration(
    { policy: policy.policy, resultMetadata: { status: "SUCCEEDED", diagnostics: [] } },
    { targetId: "apple-mobileconfig-legacy" }
  );

  assert.equal(result.ok, true);
  assert.equal(result.targetId, "apple-mobileconfig-legacy");
  assert.equal(result.outputFormat, "plist");
  assert.match(result.artifact, /com\.apple\.dnsSettings\.managed/);
});

import {
  getPlatformManifest,
  listPlatformManifests,
  getPlatformTargets,
  isTargetCompatible,
  assertTargetCompatible
} from "../packages/targets/src/platform-registry.js";

test("device platform registry covers mobile and PC families", () => {
  const ids = listPlatformManifests().map(x => x.id);
  assert.deepEqual(ids, ["ios", "ipados", "macos", "android", "windows", "linux"]);

  assert.ok(getPlatformManifest("android"));
  assert.ok(getPlatformManifest("windows"));
  assert.ok(getPlatformManifest("linux"));
  assert.ok(getPlatformManifest("macos"));
});

test("Android and PC platforms expose only explicitly compatible exporters", () => {
  assert.deepEqual(getPlatformTargets("android"), ["wireguard"]);
  assert.deepEqual(getPlatformTargets("windows"), ["wireguard", "mihomo"]);
  assert.deepEqual(getPlatformTargets("linux"), ["wireguard", "mihomo", "stash"]);
  assert.equal(isTargetCompatible("android", "wireguard"), true);
  assert.equal(isTargetCompatible("android", "surge"), false);
  assert.equal(isTargetCompatible("windows", "wireguard"), true);
  assert.equal(isTargetCompatible("linux", "mihomo"), true);
});

test("platform compatibility fails closed", () => {
  assert.throws(
    () => assertTargetCompatible("android", "surge"),
    /not registered for platform android/
  );
  assert.throws(
    () => assertTargetCompatible("chromeos", "wireguard"),
    /Unknown device platform/
  );
});
