import test from "node:test";
import assert from "node:assert/strict";
import { createProviderFlowIoContract, validateProviderFlowIoContract, ProviderFlowState } from "../packages/apple-adapter/src/provider-flow-io-contract.js";
import { createProviderFlowIoEngine } from "../packages/apple-adapter/src/provider-flow-io-runtime.js";
test("flow I/O contract is deterministic and fail-closed",()=>{const c=createProviderFlowIoContract({});const r=validateProviderFlowIoContract(c);assert.equal(r.valid,true);assert.deepEqual(c.transports,["UDP","TCP"]);assert.equal(c.safety.noDeprecatedUdpApi,true);});
test("unknown transport is rejected without retention",()=>{const e=createProviderFlowIoEngine({contract:createProviderFlowIoContract({})});const r=e.accept({id:"f1",transport:"QUIC"});assert.equal(r.accepted,false);assert.equal(r.state,ProviderFlowState.FAILED);assert.equal(e.activeCount,0);});
test("accepted flow is retained and opened before I/O",async()=>{const calls=[];const e=createProviderFlowIoEngine({contract:createProviderFlowIoContract({}),handlers:{open:async()=>calls.push("open"),read:async()=>{calls.push("read");return "data";},write:async()=>calls.push("write")}});assert.equal(e.accept({id:"f1",transport:"UDP"}).accepted,true);await assert.rejects(()=>e.read("f1"),x=>x.code==="PROVIDER_FLOW_READ_BEFORE_OPEN");assert.equal((await e.open("f1","local")).state,ProviderFlowState.OPEN);assert.equal(await e.read("f1"),"data");await e.write("f1","reply");assert.deepEqual(calls,["open","read","write"]);assert.equal(e.close("f1").state,ProviderFlowState.CLOSED);assert.equal(e.activeCount,0);});
test("open failure is terminal and releases retained flow",async()=>{const e=createProviderFlowIoEngine({contract:createProviderFlowIoContract({}),handlers:{open:async()=>{throw new Error("open failed");}}});assert.equal(e.accept({id:"f1",transport:"TCP"}).accepted,true);assert.equal((await e.open("f1","local")).state,ProviderFlowState.FAILED);assert.equal(e.activeCount,0);});
test("invalid contract blocks engine",()=>{const e=createProviderFlowIoEngine({contract:{version:"0"}});assert.equal(e.valid,false);assert.equal(e.accept({id:"f1",transport:"UDP"}).accepted,false);});
