import React,{useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {compatibilityReport} from "../../../packages/core/src/index.js";
import {exportFormats,getExportArtifact,getExportWarnings} from "../../../packages/targets/src/exporters.js";
import {recommendedDnsServices} from "../../../packages/catalog/src/recommended-dns.js";
import "./style.css";

const wizardSteps=[{id:"dns",title:"DNS",description:"Resolver profiles และ DNS transport"},{id:"wifi",title:"Wi-Fi",description:"เครือข่าย Wi-Fi"},{id:"vpn",title:"VPN",description:"VPN และ routing"},{id:"proxy",title:"Proxy",description:"Proxy และ routing action"},{id:"webapp",title:"Web App",description:"Web App / Web Clip"},{id:"review",title:"Review / Export",description:"ตรวจสอบและส่งออก"}];
const primaryTargets=["apple-mobileconfig","surge","shadowrocket","quantumult-x","wireguard","loon","stash","mihomo"];
function downloadFile(name,text,mime){const blob=new Blob([text],{type:mime});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);}
function makeBlob(name,text,mime){return new File([text],name,{type:mime});}
async function shareFile(file){if(!navigator.share||!navigator.canShare||!navigator.canShare({files:[file]}))return false;try{await navigator.share({files:[file],title:file.name});return true}catch(error){return error?.name==="AbortError";}}
function App(){
const [language,setLanguage]=useState("th"),[name,setName]=useState("Configuration Standard"),[currentStep,setCurrentStep]=useState(0),[skipped,setSkipped]=useState(()=>new Set()),[dns,setDns]=useState(true);
const [dnsProfiles,setDnsProfiles]=useState([{id:"privacy-dns",name:"Privacy DNS",preset:"cloudflare-standard",provider:"Cloudflare 1.1.1.1",protocol:"HTTPS",servers:["1.1.1.1","1.0.0.1"],endpoint:"https://cloudflare-dns.com/dns-query",role:"privacy",enabled:true,order:1},{id:"security-dns",name:"Security DNS",preset:"quad9-secure",provider:"Quad9 Secure",protocol:"HTTPS",servers:["9.9.9.9","149.112.112.112"],endpoint:"https://dns.quad9.net/dns-query",role:"security",enabled:true,order:2},{id:"backup-dns",name:"Backup DNS",preset:"google-public-dns",provider:"Google Public DNS",protocol:"HTTPS",servers:["8.8.8.8","8.8.4.4"],endpoint:"https://dns.google/dns-query",role:"resolver",enabled:true,order:3}]);
const [wifiSSID,setWifiSSID]=useState(""),[wifiPassword,setWifiPassword]=useState(""),[wifiHidden,setWifiHidden]=useState(false),[vpn,setVpn]=useState(false);
const [vpnRemoteAddress,setVpnRemoteAddress]=useState(""),[vpnRemoteIdentifier,setVpnRemoteIdentifier]=useState(""),[vpnLocalIdentifier,setVpnLocalIdentifier]=useState(""),[vpnSharedSecret,setVpnSharedSecret]=useState("");
const [proxyServer,setProxyServer]=useState(""),[proxyType,setProxyType]=useState("HTTP"),[routingAction,setRoutingAction]=useState("DIRECT"),[blockedDomains,setBlockedDomains]=useState(""),[blockPreset,setBlockPreset]=useState("custom"),[malware,setMalware]=useState(false),[trackers,setTrackers]=useState(false);
const [webAppUrl,setWebAppUrl]=useState(()=>window.location.href.split("#")[0]),[applePayloads,setApplePayloads]=useState({dns:true,webclip:true,wifi:false,vpn:false,globalProxy:false}),[target,setTarget]=useState("apple-mobileconfig"),[message,setMessage]=useState("");
const tr=language==="th"?{title:"Configuration Platform",subtitle:"สร้างไฟล์ตั้งค่าเครือข่าย แล้วเลือกวิธีนำไปติดตั้งหรือเปิดด้วยแอปที่ต้องการ",language:"ภาษา",thai:"ไทย",english:"English",knowledge:"คู่มือ",ready:"พร้อมส่งออก",notReady:"ต้องแก้ข้อมูลก่อนส่งออก",apple:"ติดตั้งบน iPhone / iPad",appleDesc:"สร้าง .mobileconfig สำหรับติดตั้งผ่าน iOS Settings",downloadProfile:"ดาวน์โหลดโปรไฟล์ iOS",installSteps:"หลังดาวน์โหลด ให้เปิด Settings > Profile Downloaded > Install",appExport:"ส่งไฟล์เข้าแอป",appDesc:"ใช้ปุ่มแชร์ของเครื่องเพื่อส่งไฟล์เข้าแอปที่รองรับ",share:"ส่งไฟล์ไปยังแอป",download:"ดาวน์โหลดไฟล์",fallback:"ถ้าแอปไม่ปรากฏในเมนูแชร์ ให้ดาวน์โหลดไฟล์แล้วนำเข้าในแอปด้วยเมนู Import",warning:"ข้อควรทราบ"}:{title:"Configuration Platform",subtitle:"Build a network configuration, then choose how to install or send it to your app.",language:"Language",thai:"ไทย",english:"English",knowledge:"Guide",ready:"Ready to export",notReady:"Fix the settings before exporting",apple:"Install on iPhone / iPad",appleDesc:"Create a .mobileconfig for installation through iOS Settings.",downloadProfile:"Download iOS profile",installSteps:"After downloading: Settings > Profile Downloaded > Install",appExport:"Send file to app",appDesc:"Use the device share sheet to send the file to a compatible app.",share:"Send to app",download:"Download file",fallback:"If the app is not shown in Share, download the file and use Import inside the app.",warning:"Important"};
const isSkipped=id=>skipped.has(id),toggleSkip=()=>setSkipped(prev=>{const next=new Set(prev),id=wizardSteps[currentStep].id;next.has(id)?next.delete(id):next.add(id);return next;}),goNext=()=>setCurrentStep(x=>Math.min(5,x+1)),goBack=()=>setCurrentStep(x=>Math.max(0,x-1));
const updateProfile=(index,patch)=>setDnsProfiles(list=>list.map((p,i)=>i===index?{...p,...patch}:p));
const selectDnsPreset=(index,id)=>{const preset=recommendedDnsServices.find(x=>x.id===id);updateProfile(index,{preset,provider:preset?.provider||"Custom",servers:preset?[...preset.ipv4,...preset.ipv6]:dnsProfiles[index].servers,protocol:preset?.doh?"HTTPS":preset?.dot?"TLS":dnsProfiles[index].protocol,endpoint:preset?.doh||""});};
const policy=useMemo(()=>{const dnsEnabled=!isSkipped("dns")&&dns,wifiEnabled=!isSkipped("wifi")&&applePayloads.wifi,vpnEnabled=!isSkipped("vpn")&&vpn,proxyEnabled=!isSkipped("proxy"),webEnabled=!isSkipped("webapp"),profiles=dnsEnabled?dnsProfiles:[],first=profiles[0];return{version:"0.5",policy:{name,vpn:vpnEnabled,dns:dnsEnabled,routing:vpnEnabled,blocking:{malware:proxyEnabled&&malware,trackers:proxyEnabled&&trackers,separateFromResolver:true},dnsProfiles:profiles,dnsServers:first?.servers||[],proxyServer:proxyEnabled?proxyServer.trim():"",dnsProtocol:first?.protocol||"",dnsServerUrl:dnsEnabled?(first?.endpoint||""):"",webAppUrl:webEnabled?webAppUrl.trim():"",dnsDomains:[],rules:proxyEnabled?[{match:"*.*",action:routingAction}]:[],finalPolicy:"DIRECT",bypassSystem:true,webEntry:{name:"Configuration Platform",url:webEnabled?webAppUrl.trim():"",enabled:webEnabled},applePayloads:{dns:dnsEnabled&&applePayloads.dns,webclip:webEnabled&&applePayloads.webclip,wifi:wifiEnabled,vpn:vpnEnabled&&applePayloads.vpn,globalProxy:proxyEnabled&&applePayloads.globalProxy},wifiSSID:wifiEnabled?wifiSSID:"",wifiPassword:wifiEnabled?wifiPassword:"",wifiHidden:wifiEnabled&&wifiHidden,vpnRemoteAddress:vpnEnabled?vpnRemoteAddress:"",vpnRemoteIdentifier:vpnEnabled?vpnRemoteIdentifier:"",vpnLocalIdentifier:vpnEnabled?vpnLocalIdentifier:"",vpnSharedSecret:vpnEnabled?vpnSharedSecret:"",blockedDomains:proxyEnabled?blockedDomains.split(/[\s,]+/).map(x=>x.trim()).filter(Boolean):[],routingAction:proxyEnabled?routingAction:"DIRECT",proxyType:proxyEnabled?proxyType:""}}},[name,vpn,dns,dnsProfiles,proxyServer,applePayloads,wifiSSID,wifiPassword,wifiHidden,vpnRemoteAddress,vpnRemoteIdentifier,vpnLocalIdentifier,vpnSharedSecret,blockedDomains,routingAction,proxyType,webAppUrl,malware,trackers,skipped]);
const selectedFormat=exportFormats.find(x=>x.id===target)||exportFormats[0],artifact=getExportArtifact(selectedFormat.id,policy),warnings=getExportWarnings(selectedFormat.id,policy),report=useMemo(()=>compatibilityReport(policy,target),[policy,target]),blocking=report.diagnostics.filter(x=>(x.level==="CRITICAL"||x.level==="HIGH")&&x.code!=="CAPABILITY_UNKNOWN"),capabilityWarnings=report.diagnostics.filter(x=>x.code==="CAPABILITY_UNKNOWN"),exportReady=Boolean(artifact)&&blocking.length===0,isApple=target==="apple-mobileconfig",primaryFormats=primaryTargets.map(id=>exportFormats.find(x=>x.id===id)).filter(Boolean);
const doDownload=()=>{downloadFile(`${selectedFormat.id}-config${selectedFormat.extension}`,artifact,selectedFormat.mime);setMessage("ดาวน์โหลดไฟล์แล้ว")},doShare=async()=>{const file=makeBlob(`${selectedFormat.id}-config${selectedFormat.extension}`,artifact,selectedFormat.mime);if(await shareFile(file))setMessage("เปิดเมนูแชร์แล้ว เลือกแอปปลายทางได้เลย");else{doDownload();setMessage("อุปกรณ์นี้ไม่รองรับการส่งไฟล์เข้าแอปโดยตรง จึงดาวน์โหลดไฟล์แทน")}};
const navButtons=<div className="wizard-actions"><button className="secondary-action" type="button" onClick={goBack} disabled={currentStep===0}>ย้อนกลับ</button><button className="primary-action" type="button" onClick={goNext} disabled={currentStep===5}>ถัดไป</button></div>;
const renderStep=()=>{if(currentStep===0)return <section className="card wizard-panel"><div className="section-title"><div><span className="step">1</span><div><h2>DNS</h2><p>จัดการ resolver profiles และ DNS transport</p></div></div></div><label>Profile name<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="check"><input type="checkbox" checked={dns} onChange={e=>setDns(e.target.checked)}/>เปิดใช้งาน DNS</label>{dnsProfiles.map((profile,index)=><div className="dns-profile-card" key={profile.id}><div className="advanced-grid"><label>ชื่อชุด DNS<input value={profile.name} onChange={e=>updateProfile(index,{name:e.target.value})}/></label><label>บริการ DNS<select value={profile.preset.id||profile.preset} onChange={e=>selectDnsPreset(index,e.target.value)}>{recommendedDnsServices.map(x=><option key={x.id} value={x.id}>{x.provider} · {x.description}</option>)}</select></label><label>Protocol<select value={profile.protocol} onChange={e=>updateProfile(index,{protocol:e.target.value})}><option>HTTPS</option><option>TLS</option><option>PLAIN</option></select></label><label>บทบาท<select value={profile.role} onChange={e=>updateProfile(index,{role:e.target.value})}><option value="resolver">Resolver</option><option value="security">Security / Threat</option><option value="privacy">Privacy</option><option value="custom">Custom</option></select></label></div><label>DNS Servers<textarea value={profile.servers.join("\n")} rows="2" onChange={e=>updateProfile(index,{servers:e.target.value.split(/[,\s]+/).filter(Boolean)})}/></label><label>Endpoint<input value={profile.endpoint} onChange={e=>updateProfile(index,{endpoint:e.target.value})}/></label><label className="check"><input type="checkbox" checked={profile.enabled} onChange={e=>updateProfile(index,{enabled:e.target.checked})}/>เปิดใช้ชุดนี้</label></div>)}{navButtons}</section>;
if(currentStep===1)return <section className="card wizard-panel"><div className="section-title"><div><span className="step">2</span><div><h2>Wi-Fi</h2><p>ตั้งค่า Wi-Fi payload</p></div></div></div><label className="check"><input type="checkbox" checked={applePayloads.wifi} onChange={e=>setApplePayloads(x=>({...x,wifi:e.target.checked}))}/>สร้าง Wi-Fi payload</label>{applePayloads.wifi&&<div className="advanced-grid"><label>SSID<input value={wifiSSID} onChange={e=>setWifiSSID(e.target.value)}/></label><label>Password<input type="password" value={wifiPassword} onChange={e=>setWifiPassword(e.target.value)}/></label><label className="check"><input type="checkbox" checked={wifiHidden} onChange={e=>setWifiHidden(e.target.checked)}/>Hidden Network</label></div>}{navButtons}</section>;
if(currentStep===2)return <section className="card wizard-panel"><div className="section-title"><div><span className="step">3</span><div><h2>VPN</h2><p>ตั้งค่า VPN และ routing</p></div></div></div><label className="check"><input type="checkbox" checked={vpn} onChange={e=>setVpn(e.target.checked)}/>เปิดใช้ VPN / Routing</label><label className="check"><input type="checkbox" checked={applePayloads.vpn} onChange={e=>setApplePayloads(x=>({...x,vpn:e.target.checked}))}/>สร้าง IKEv2 VPN payload</label>{applePayloads.vpn&&<div className="advanced-grid"><label>Remote Address<input value={vpnRemoteAddress} onChange={e=>setVpnRemoteAddress(e.target.value)}/></label><label>Remote Identifier<input value={vpnRemoteIdentifier} onChange={e=>setVpnRemoteIdentifier(e.target.value)}/></label><label>Local Identifier<input value={vpnLocalIdentifier} onChange={e=>setVpnLocalIdentifier(e.target.value)}/></label><label>Shared Secret<input type="password" value={vpnSharedSecret} onChange={e=>setVpnSharedSecret(e.target.value)}/></label></div>}{navButtons}</section>;
if(currentStep===3)return <section className="card wizard-panel"><div className="section-title"><div><span className="step">4</span><div><h2>Proxy</h2><p>Proxy, routing action และ blocklist</p></div></div></div><div className="advanced-grid"><label>Proxy type<select value={proxyType} onChange={e=>setProxyType(e.target.value)}><option>HTTP</option><option>HTTPS</option><option>SOCKS5</option></select></label><label>Routing action<select value={routingAction} onChange={e=>setRoutingAction(e.target.value)}><option>DIRECT</option><option>PROXY</option><option>REJECT</option><option>DNS</option></select></label></div><label>Proxy Server<input value={proxyServer} onChange={e=>setProxyServer(e.target.value)}/></label><label>Blocked domains<textarea value={blockedDomains} onChange={e=>setBlockedDomains(e.target.value)} rows="4"/></label><label>Blocklist preset<select value={blockPreset} onChange={e=>setBlockPreset(e.target.value)}><option value="custom">Custom</option><option value="oisd-small">OISD Small</option><option value="hagezi-pro">HaGeZi Pro</option><option value="hagezi-tif">HaGeZi Threat Intelligence</option></select></label><label className="check"><input type="checkbox" checked={malware} onChange={e=>setMalware(e.target.checked)}/>บล็อก Malware</label><label className="check"><input type="checkbox" checked={trackers} onChange={e=>setTrackers(e.target.checked)}/>บล็อก Tracker</label>{navButtons}</section>;
if(currentStep===4)return <section className="card wizard-panel"><div className="section-title"><div><span className="step">5</span><div><h2>Web App</h2><p>กำหนด Web App / Web Clip</p></div></div></div><label>Web App URL<input value={webAppUrl} onChange={e=>setWebAppUrl(e.target.value)}/></label><label className="check"><input type="checkbox" checked={applePayloads.webclip} onChange={e=>setApplePayloads(x=>({...x,webclip:e.target.checked}))}/>สร้าง Web Clip / Web App payload</label>{navButtons}</section>;
return <section className="card export-card wizard-panel"><div className="section-title"><div><span className="step">6</span><div><h2>Review / Export</h2><p>ตรวจสอบ compatibility และส่งออก</p></div></div></div><div className="review-summary"><strong>Profile:</strong> {name}<br/><strong>Skipped:</strong> {Array.from(skipped).join(", ")||"none"}</div><h3>Target</h3><div className="target-grid">{primaryFormats.map(format=><button key={format.id} type="button" className={target===format.id?"target-card selected":"target-card"} onClick={()=>setTarget(format.id)}><strong>{format.label}</strong><span>{format.extension}</span><small>{format.description}</small></button>)}</div><div className={exportReady?"status ready":"status not-ready"}><strong>{exportReady?tr.ready:tr.notReady}</strong>{!exportReady&&<ul>{blocking.map((x,i)=><li key={i}>{x.message}</li>)}</ul>}</div>{isApple?<div className="install-box"><h3>{tr.apple}</h3><p>{tr.appleDesc}</p><button className="primary-action" disabled={!artifact} onClick={()=>downloadFile("configuration-profile.mobileconfig",artifact,"application/x-apple-aspen-config")}>{tr.downloadProfile}</button><ol><li>{tr.downloadProfile}</li><li>{tr.installSteps}</li></ol></div>:<div className="install-box"><h3>{tr.appExport}: {selectedFormat.label}</h3><p>{tr.appDesc}</p><button className="primary-action" disabled={!artifact} onClick={doShare}>{tr.share}</button><button className="secondary-action" disabled={!artifact} onClick={doDownload}>{tr.download}</button><p className="fallback">{tr.fallback}</p></div>}{(warnings.length||capabilityWarnings.length)>0&&<div className="warning"><strong>{tr.warning}</strong><ul>{warnings.map((w,i)=><li key={i}>{w.message}</li>)}{capabilityWarnings.map((w,i)=><li key={"c"+i}>{w.message}</li>)}</ul></div>}{message&&<div className="message">{message}</div>}<details className="technical-details"><summary>รายละเอียดทางเทคนิค</summary><pre>{artifact}</pre></details>{navButtons}</section>};
const step=wizardSteps[currentStep];
return <main><header className="hero"><div className="language-menu"><label>{tr.language}<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="th">{tr.thai}</option><option value="en">{tr.english}</option></select></label></div><div className="hero-badge">Configuration Compiler</div><h1>{tr.title}</h1><p>{tr.subtitle}</p><a href="./knowledge.html">{tr.knowledge}</a></header><nav className="wizard-nav" aria-label="Configuration wizard">{wizardSteps.map((item,index)=><button key={item.id} type="button" className={currentStep===index?"wizard-step active":isSkipped(item.id)?"wizard-step skipped":"wizard-step"} onClick={()=>setCurrentStep(index)}><span>{index+1}</span><strong>{item.title}</strong><small>{isSkipped(item.id)?"Skipped":item.description}</small></button>)}</nav><div className="wizard-toolbar"><span>ขั้นตอน {currentStep+1} / 6: <strong>{step.title}</strong></span><button type="button" className={isSkipped(step.id)?"skip-button active":"skip-button"} onClick={toggleSkip}>{isSkipped(step.id)?"ยกเลิก Skip":"Skip ขั้นตอนนี้"}</button></div>{renderStep()}</main>;
}
createRoot(document.getElementById("root")).render(<App/>);
