import React,{useMemo,useState} from "react";
import {compatibilityReport,listTargetManifests,searchRecords,configurationExporter} from "../../../packages/core/src/index.js";
import {exportFormats} from "../../../packages/targets/src/exporters.js";
import {recommendedDnsServices} from "../../../packages/catalog/src/recommended-dns.js";
import {configurationWizard} from "./wizard.js";
import {applyWizardSkipSemantics,configurationWizardSteps} from "./wizard-steps.js";

const tr={th:{title:"Configuration Platform",subtitle:"ค้นหา → กำหนดค่า → ตรวจ compatibility → ส่งออก",profileName:"ชื่อโปรไฟล์",next:"ถัดไป",back:"ย้อนกลับ",skip:"ข้ามขั้นตอน",reset:"เริ่มใหม่",search:"ค้นหา Target / DNS / Provider",hint:"เช่น Surge, Shadowrocket, Cloudflare, DoH",noResults:"ไม่พบรายการ",intent:"Intent",source:"Source",dns:"DNS / Policy",target:"Target",compatibility:"Compatibility",review:"Review / Export",ready:"พร้อมส่งออก",notReady:"ต้องแก้ข้อมูลก่อนส่งออก",warning:"ข้อควรทราบ",knowledge:"คู่มือ"},en:{title:"Configuration Platform",subtitle:"Search → Configure → Verify compatibility → Export",profileName:"Profile name",next:"Next",back:"Back",skip:"Skip step",reset:"Start over",search:"Search Target / DNS / Provider",hint:"e.g. Surge, Shadowrocket, Cloudflare, DoH",noResults:"No results",intent:"Intent",source:"Source",dns:"DNS / Policy",target:"Target",compatibility:"Compatibility",review:"Review / Export",ready:"Ready to export",notReady:"Fix the configuration before exporting",warning:"Important",knowledge:"Guide"}};
const capabilityStateText={SUPPORTED:"รองรับ",LIMITED:"รองรับแบบมีข้อจำกัด",TRANSFORMABLE:"แปลงความหมายได้",LOSSY:"แปลงได้แต่มีข้อมูล/พฤติกรรมสูญเสีย",UNSUPPORTED:"ไม่รองรับ",UNKNOWN:"ยังไม่ยืนยัน","NOT REQUESTED":"ไม่ได้ร้องขอ"};
const capabilityStateTextEn={SUPPORTED:"Supported",LIMITED:"Limited",TRANSFORMABLE:"Transformable",LOSSY:"Lossy",UNSUPPORTED:"Unsupported",UNKNOWN:"Unverified","NOT REQUESTED":"Not requested"};
function downloadFile(name,text,mime){const u=URL.createObjectURL(new Blob([text],{type:mime}));const a=document.createElement("a");a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000)}
async function shareFile(file){if(!navigator.share||!navigator.canShare||!navigator.canShare({files:[file]}))return false;try{await navigator.share({files:[file],title:file.name});return true}catch(e){return e?.name==="AbortError"}}
function androidBridgeAvailable(){return typeof window.AndroidExport?.sendToApp==="function"&&typeof window.AndroidExport?.saveFile==="function"}
export function WizardApp(){
 const [language,setLanguage]=useState("th"),T=tr[language]; const [name,setName]=useState("Configuration Standard"),[vpn,setVpn]=useState(false),[dns,setDns]=useState(true),[malware,setMalware]=useState(false),[trackers,setTrackers]=useState(false),[proxyServer,setProxyServer]=useState(""),[routingAction,setRoutingAction]=useState("DIRECT"),[proxyType,setProxyType]=useState("HTTP"),[query,setQuery]=useState(""),[target,setTarget]=useState("apple-mobileconfig"),[message,setMessage]=useState(""),[skipped,setSkipped]=useState(()=>new Set());
 const [dnsProfiles,setDnsProfiles]=useState(()=>recommendedDnsServices.filter(x=>["cloudflare-standard","quad9-secure","google-public-dns"].includes(x.id)).map((d,i)=>({id:d.id,name:i===0?"Privacy DNS":i===1?"Security DNS":"Backup DNS",preset:d.id,provider:d.provider,protocol:d.doh?"HTTPS":d.dot?"TLS":"DNS",servers:[...(d.ipv4||[]),...(d.ipv6||[])],endpoint:d.doh||"",role:i===0?"privacy":i===1?"security":"backup",enabled:true,order:i+1})));
 const [applePayloads,setApplePayloads]=useState({dns:true,webclip:true,wifi:false,vpn:false,globalProxy:false});
 const [blockedDomains,setBlockedDomains]=useState("");
 const manifests=useMemo(()=>listTargetManifests(),[]), formats=useMemo(()=>new Map(exportFormats.map(x=>[x.id,x])),[]), registry=useMemo(()=>new Map(manifests.map(x=>[x.id,x])),[manifests]);
 const searchIndex=useMemo(()=>[...manifests.map((m,i)=>({id:m.id,name:formats.get(m.id)?.label||m.id,provider:"Target Registry",role:"target",description:(m.limitations||[]).join(" "),tags:[m.status,m.version],sourceIndex:i})),...recommendedDnsServices.map((d,i)=>({id:d.id,name:d.provider,provider:d.provider,protocol:d.doh?"DoH":d.dot?"DoT":"DNS",role:"dns",endpoint:d.doh||d.dot||"",description:d.description,tags:["dns","resolver"],sourceIndex:manifests.length+i}))],[manifests,formats]);
 const results=useMemo(()=>query.trim()?searchRecords(searchIndex,query).slice(0,8):[],[searchIndex,query]), selected=registry.get(target),format=formats.get(target);
 const policy=useMemo(()=>({version:"0.6",policy:{name,vpn,dns,routing:vpn,blocking:{malware,trackers,separateFromResolver:true},dnsProfiles:dns?dnsProfiles:[],dnsServers:dns&&dnsProfiles[0]?dnsProfiles[0].servers:[],proxyServer:proxyServer.trim(),dnsProtocol:dnsProfiles[0]?.protocol||"HTTPS",dnsServerUrl:dnsProfiles[0]?.endpoint||"",webAppUrl:window.location.href.split("#")[0],dnsDomains:[],rules:[{match:"*.*",action:routingAction}],finalPolicy:"DIRECT",bypassSystem:true,webEntry:{name:"Configuration Platform",url:window.location.href.split("#")[0],enabled:true},applePayloads,blockedDomains:blockedDomains.split(/[\\s,]+/).map(x=>x.trim()).filter(Boolean),routingAction,proxyType}}),[name,vpn,dns,dnsProfiles,proxyServer,routingAction,applePayloads,blockedDomains,proxyType]);
 const effective=useMemo(()=>applyWizardSkipSemantics(policy,skipped),[policy,skipped]),report=useMemo(()=>compatibilityReport(effective,target),[effective,target]),exportResult=useMemo(()=>report.exportable?configurationExporter.export({status:"SUCCESS",policy:report.policy,resultMetadata:{}},target):null,[report,target]),artifact=exportResult?.artifact||"",warnings=exportResult?.diagnostics?.filter(x=>x.level==="WARNING")||[];
 const blocking=report.diagnostics.filter(x=>x.level==="CRITICAL"||x.level==="HIGH"),unknown=report.diagnostics.filter(x=>x.code==="CAPABILITY_UNKNOWN"),extensionBacked=Boolean(selected?.limitations?.some(x=>/extension|provider app|network extension/i.test(x))),ready=Boolean(artifact)&&report.exportable;
 const stepper=configurationWizard.useStepper({linear:true}); const index=id=>configurationWizardSteps.findIndex(x=>x.id===id);
 const select=id=>{if(formats.has(id)){setTarget(id);setMessage("")}}; const next=async()=>stepper.canNext&&stepper.next(); const prev=async()=>stepper.canPrev&&stepper.prev(); const skip=async()=>{if(stepper.current.skippable&&stepper.canNext){setSkipped(s=>new Set(s).add(stepper.current.id));await stepper.next()}}; const reset=async()=>{await stepper.reset();setSkipped(new Set());setMessage("")};
 const saveDownload=()=>{if(ready){if(androidBridgeAvailable()){window.AndroidExport.saveFile(target+"-config"+format.extension,format.mime,artifact);setMessage(language==="th"?"เปิดตัวเลือกบันทึกไฟล์แล้ว":"Save location opened");return}downloadFile(target+"-config"+format.extension,artifact,format.mime);setMessage(language==="th"?"ดาวน์โหลดไฟล์แล้ว":"File downloaded")}};
 const saveShare=async()=>{if(!ready)return;const fileName=target+"-config"+format.extension;if(androidBridgeAvailable()){window.AndroidExport.sendToApp(fileName,format.mime,artifact);setMessage(language==="th"?"เปิดเมนูส่งไปยังแอปแล้ว":"App chooser opened");return}const f=new File([artifact],fileName,{type:format.mime});if(await shareFile(f))setMessage(language==="th"?"เปิดเมนูแชร์แล้ว":"Share sheet opened");else saveDownload()};
 const title=s=>T[s.id]||s.title;
 return <main>
  <header className="hero"><div className="language-menu"><label>ภาษา<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="th">ไทย</option><option value="en">English</option></select></label></div><div className="hero-badge">Configuration Compiler · Extensible UI</div><h1>{T.title}</h1><p>{T.subtitle}</p><div className="wizard-meta"><span>Step {stepper.index+1} / {stepper.count}</span><a href="./knowledge.html">{T.knowledge}</a></div></header>
  <section className="card search-workspace"><div className="search-heading"><div><span className="eyebrow">DISCOVERY</span><h2>{T.search}</h2><p>{T.hint}</p></div><span className="source-badge">Registry + Catalog</span></div><label className="search-input-wrap"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={T.hint}/>{query&&<button type="button" onClick={()=>setQuery("")}>×</button>}</label>{query?<div className="search-results">{results.length?results.map(r=><button className="search-result" type="button" key={r.role+r.id} onClick={()=>{if(r.role==="target")select(r.id);setQuery("")}}><span className="result-kind">{r.role}</span><span><strong>{r.name}</strong><small>{r.id} · {r.provider}</small></span></button>):<p className="empty-search">{T.noResults}</p>}</div>:<div className="quick-targets">{manifests.filter(m=>formats.has(m.id)).map(m=><button type="button" key={m.id} className={target===m.id?"quick-target selected":"quick-target"} onClick={()=>select(m.id)}>{formats.get(m.id).label}</button>)}</div>}</section>
  <section className="wizard-shell"><ol className="wizard-progress">{configurationWizardSteps.map((s,i)=>{const state=i===stepper.index?"active":i<stepper.index?"previous":"upcoming";return <li key={s.id} className={"wizard-step "+state}><button type="button" disabled={i>stepper.index} onClick={()=>i<=stepper.index&&stepper.goTo(s.id)}><span className="wizard-index">{i+1}</span><span><strong>{title(s)}</strong><small>{s.description}</small></span></button></li>})}</ol>
   <section className="card wizard-panel"><div className="section-title"><div><span className="step">{stepper.index+1}</span><div><h2>{title(stepper.current)}</h2><p>{stepper.current.description}</p></div></div></div>
   {stepper.is("intent")&&<div className="wizard-content"><p>กำหนดความหมายของ configuration ก่อนเลือก target เพื่อให้ target-specific implementation อยู่ที่ adapter boundary</p><label>{T.profileName}<input value={name} onChange={e=>setName(e.target.value)}/></label><div className="info-grid"><div><strong>Core-first</strong><span>Canonical policy เป็นศูนย์กลาง</span></div><div><strong>Target isolation</strong><span>Registry และ exporter แยกจาก UI</span></div><div><strong>Evidence-aware</strong><span>ไม่อ้าง capability ที่ยังไม่ verified</span></div></div></div>}
   {stepper.is("source")&&<div className="wizard-content"><div className="advanced-grid"><label>Proxy type<select value={proxyType} onChange={e=>setProxyType(e.target.value)}><option>HTTP</option><option>HTTPS</option><option>SOCKS5</option></select></label><label>Routing action<select value={routingAction} onChange={e=>setRoutingAction(e.target.value)}><option>DIRECT</option><option>PROXY</option><option>REJECT</option><option>DNS</option></select></label></div><label>Proxy Server<input value={proxyServer} onChange={e=>setProxyServer(e.target.value)} placeholder="proxy.example.com:8080"/></label><label>Blocked domains<textarea value={blockedDomains} onChange={e=>setBlockedDomains(e.target.value)} rows="4" placeholder="example.com, ads.example.com"/></label><label className="check"><input type="checkbox" checked={vpn} onChange={e=>setVpn(e.target.checked)}/>เปิดใช้ VPN / Routing</label><label className="check"><input type="checkbox" checked={malware} onChange={e=>setMalware(e.target.checked)}/>บล็อก Malware</label><label className="check"><input type="checkbox" checked={trackers} onChange={e=>setTrackers(e.target.checked)}/>บล็อก Tracker</label></div>}
   {stepper.is("dns")&&<div className="wizard-content"><label className="check"><input type="checkbox" checked={dns} onChange={e=>setDns(e.target.checked)}/>เปิดใช้ DNS configuration</label>{dnsProfiles.map((p,i)=><div className="dns-profile-card" key={p.id}><div className="advanced-grid"><label>ชื่อชุด DNS<input value={p.name} onChange={e=>setDnsProfiles(a=>a.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/></label><label>บริการ DNS<select value={p.preset} onChange={e=>{const d=recommendedDnsServices.find(x=>x.id===e.target.value);setDnsProfiles(a=>a.map((x,j)=>j===i?{...x,preset:e.target.value,provider:d?.provider||"Custom",servers:d?[...d.ipv4,...d.ipv6]:x.servers,protocol:d?.doh?"HTTPS":d?.dot?"TLS":x.protocol,endpoint:d?.doh||x.endpoint}:x))}}>{recommendedDnsServices.map(d=><option key={d.id} value={d.id}>{d.provider}</option>)}</select></label></div><label>DNS Servers<textarea value={p.servers.join("\n")} rows="3" onChange={e=>setDnsProfiles(a=>a.map((x,j)=>j===i?{...x,servers:e.target.value.split(/[,\s]+/).filter(Boolean)}:x))}/></label><label>Endpoint<input value={p.endpoint} onChange={e=>setDnsProfiles(a=>a.map((x,j)=>j===i?{...x,endpoint:e.target.value}:x))}/></label><label className="check"><input type="checkbox" checked={p.enabled!==false} onChange={e=>setDnsProfiles(a=>a.map((x,j)=>j===i?{...x,enabled:e.target.checked}:x))}/>เปิดใช้ชุด DNS นี้</label>{dnsProfiles.length>1&&<button type="button" className="secondary-action" onClick={()=>setDnsProfiles(a=>a.filter((_,j)=>j!==i))}>ลบชุดนี้</button>}</div>)}<div className="dns-profile-actions"><button type="button" className="secondary-action" onClick={()=>setDnsProfiles(a=>[...a,{id:"custom-"+Date.now(),name:"Custom DNS "+(a.length+1),preset:"cloudflare-standard",provider:"Custom",protocol:"HTTPS",servers:[],endpoint:"",role:"resolver",enabled:true,order:a.length+1}])}>เพิ่มชุด DNS</button></div></div>}
   {stepper.is("target")&&<div className="wizard-content"><div className="selected-target-banner"><div><span className="eyebrow">TARGET REGISTRY</span><h3>{format?.label||target}</h3><p><code>{target}</code> · {selected?.status||"unknown"} · {selected?.version||"n/a"}</p></div><span className="registry-dot">●</span></div><div className="target-grid">{manifests.filter(m=>formats.has(m.id)).map(m=><button type="button" key={m.id} className={target===m.id?"target-card selected":"target-card"} onClick={()=>select(m.id)}><strong>{formats.get(m.id).label}</strong><span>{formats.get(m.id).extension}</span><small>{m.status} · {m.version}</small></button>)}</div>{target==="apple-mobileconfig"&&<details open><summary>Apple Payloads</summary><div className="advanced-grid">{Object.entries({dns:"Encrypted DNS payload",webclip:"Web Clip / Web App payload",wifi:"Wi-Fi payload",vpn:"IKEv2 VPN payload",globalProxy:"Global HTTP Proxy payload"}).map(([k,v])=><label className="check" key={k}><input type="checkbox" checked={applePayloads[k]} onChange={e=>setApplePayloads(x=>({...x,[k]:e.target.checked}))}/>{v}</label>)}</div></details>}</div>}
   {stepper.is("compatibility")&&<div className="wizard-content"><div className={ready?"status ready":"status not-ready"}><strong>{ready?T.ready:T.notReady}</strong>{blocking.length>0&&<ul>{blocking.map((x,i)=><li key={i}>{x.message}</li>)}</ul>}</div><div className="selected-target-banner compact"><div><span className="eyebrow">TARGET</span><h3>{format?.label||target}</h3><p>{selected?.status||"unknown"} · Evidence {selected?.evidence?.length||0}</p></div></div><div className="compatibility-list">{Object.entries(report.capabilities).map(([k,v])=>{const state=v.requested?v.state:"NOT REQUESTED";const label=language==="th"?capabilityStateText[state]:capabilityStateTextEn[state];return <div className="row" key={k}><span>{k}<small className="capability-note">{label}</small></span><strong>{state}</strong></div>})}</div>{(warnings.length||unknown.length||extensionBacked)>0&&<div className="warning"><strong>{T.warning}</strong>{extensionBacked&&<p className="capability-note">EXTENSION-BACKED: ความสามารถบางส่วนของ Target นี้อาจต้องใช้ Provider App หรือ Network Extension เพิ่มเติม; สถานะนี้ไม่ใช่หลักฐานว่า runtime ทำงานจริง</p>}<ul>{warnings.map((x,i)=><li key={i}>{x.message}</li>)}{unknown.map((x,i)=><li key={"u"+i}>{x.message}</li>)}</ul></div>}</div>}
   {stepper.is("review")&&<div className="wizard-content"><div className={ready?"status ready":"status not-ready"}><strong>{ready?T.ready:T.notReady}</strong><p>Target: {format?.label||target} · Output: {format?.extension||"—"}</p></div>{selected?.limitations?.length>0&&<div className="warning"><strong>Target limitations</strong><ul>{selected.limitations.map((x,i)=><li key={i}>{x}</li>)}</ul></div>}<div className="review-grid"><div><span>Profile</span><strong>{name}</strong></div><div><span>Target</span><strong>{format?.label||target}</strong></div><div><span>DNS</span><strong>{effective.policy.dns?"Enabled":"Disabled"}</strong></div><div><span>Diagnostics</span><strong>{report.diagnostics.length}</strong></div></div>{ready?<><button type="button" className="primary-action" onClick={saveDownload}>Download {format.extension}</button><button type="button" className="secondary-action" onClick={saveShare}>Share / Send to app</button></>:<div className="fallback">Export is blocked until compatibility diagnostics are resolved.</div>}{message&&<div className="message">{message}</div>}<details className="technical-details"><summary>Technical artifact preview</summary><pre>{artifact||"No artifact generated"}</pre></details></div>}
   <div className="wizard-actions"><button type="button" className="secondary-action wizard-button" onClick={prev} disabled={!stepper.canPrev}>{T.back}</button>{stepper.current.skippable&&<button type="button" className="secondary-action wizard-button" onClick={skip}>{T.skip}</button>}{stepper.canNext?<button type="button" className="primary-action wizard-button" onClick={next}>{T.next}</button>:<button type="button" className="secondary-action wizard-button" onClick={reset}>{T.reset}</button>}</div>
   </section>
  </section>
 </main>
}