plugins { id "com.android.application" }

android {
    namespace "com.prasong.networkconfiguration"
    compileSdk 36

    defaultConfig {
        applicationId "com.prasong.networkconfiguration"
        minSdk 31
        targetSdk 36
        versionCode 1
        versionName "0.1.0"
    }

    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }

    dependencies {
        implementation "androidx.webkit:webkit:1.17.1"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
