import { compileSurge } from "../../surge-adapter/src/index.js";
import { compileAppleMobileConfig, compileAppleDeclarativeDns } from "../../apple-adapter/src/index.js";

const list=v=>Array.isArray(v)?v:[];
const policyOf=input=>input?.policy&&typeof input.policy==="object"?input.policy:(input||{});
function profiles(p){const x=list(p.dnsProfiles).filter(v=>v&&v.enabled!==false);if(x.length)return x;const s=list(p.dnsServers).filter(Boolean);return s.length?[{id:"dns-default",name:"DNS",protocol:p.dnsProtocol||"HTTPS",servers:s,endpoint:p.dnsServerUrl||""}]:[];}
function servers(p){return profiles(p).flatMap(x=>list(x.servers).filter(Boolean));}
function rules(p){return list(p.rules).map((r,i)=>({type:r?.type||(r?.domainSuffix?"DOMAIN-SUFFIX":r?.domain?"DOMAIN":"DOMAIN"),value:r?.value||r?.domainSuffix||r?.domain||r?.match||"*",action:r?.policy||r?.action||"DIRECT",id:r?.id||`rule-${i+1}`}));}
function blocked(p){return [...new Set([...list(p.blockedDomains),...rules(p).filter(r=>/REJECT|BLOCK/i.test(r.action)).map(r=>r.value).filter(v=>v&&v!=="*")])];}
function proxies(p){return list(p.proxies).filter(x=>x&&typeof x==="object"&&x.name&&x.type&&x.server&&x.port);}
function proxyGroups(p){return list(p.proxyGroups).filter(x=>x&&typeof x==="object"&&x.name&&x.type);}
function proxyOptions(x){const out=[];if(x.username)out.push("username="+x.username);if(x.password)out.push("password="+x.password);if(x.tls===true)out.push("tls=true");if(x.udp===true)out.push("udp=true");return out;}
function yaml(v){return v===null||v===undefined?"null":typeof v==="boolean"||typeof v==="number"?String(v):JSON.stringify(String(v));}
function yamlList(v,indent=""){return list(v).map(x=>`${indent}- ${yaml(x)}`).join("\n");}

function exportMihomo(p){
  const ps=proxies(p), gs=proxyGroups(p);
  return ["# Generated by Configuration Platform","dns:","  enable: true","  nameserver:",yamlList(servers(p),"    "),"proxies:",
    ...ps.flatMap(x=>["  - name: "+yaml(x.name),"    type: "+yaml(x.type),"    server: "+yaml(x.server),"    port: "+x.port, ...(x.username?["    username: "+yaml(x.username)]:[]), ...(x.password?["    password: "+yaml(x.password)]:[]), ...(x.tls!==undefined?["    tls: "+Boolean(x.tls)]:[]), ...(x.udp!==undefined?["    udp: "+Boolean(x.udp)]:[])]),
    "proxy-groups:",
    ...(gs.length?gs.flatMap(g=>["  - name: "+yaml(g.name),"    type: "+yaml(g.type),...(list(g.proxies).length?["    proxies:",...list(g.proxies).map(x=>"      - "+yaml(x))]:[])]):["  - name: DIRECT","    type: select","    proxies:","      - DIRECT"]),
    "rules:",...rules(p).map(r=>"  - "+r.type+","+r.value+","+r.action),"  - MATCH,DIRECT",""].join("\n");
}
function exportStash(p){
  return exportMihomo(p);
}
function exportWireGuard(p){
  const out=["# Generated by Configuration Platform","[Interface]"];if(servers(p).length)out.push("DNS = "+servers(p).join(", "));if(p.vpnAddress)out.push("Address = "+p.vpnAddress);if(p.vpnPrivateKey)out.push("PrivateKey = "+p.vpnPrivateKey);out.push("","[Peer]");if(p.vpnPublicKey)out.push("PublicKey = "+p.vpnPublicKey);if(p.vpnEndpoint)out.push("Endpoint = "+p.vpnEndpoint);if(list(p.vpnAllowedIPs).length)out.push("AllowedIPs = "+p.vpnAllowedIPs.join(", "));if(p.vpnPersistentKeepalive)out.push("PersistentKeepalive = "+p.vpnPersistentKeepalive);out.push("");return out.join("\n");
}
function exportShadowrocket(p){
  const ps=proxies(p), gs=proxyGroups(p);
  return ["[General]","dns-server = "+servers(p).join(", "),"bypass-system = "+(p.bypassSystem!==false?"true":"false"),"","[Proxy]",...ps.map(x=>x.name+" = "+x.type+", "+x.server+", "+x.port+(x.username?", "+x.username:"")+(x.password?", "+x.password:"")+(x.tls===true?", tls=true":"")+(x.udp===true?", udp=true":"")),"","[Proxy Group]",...(gs.length?gs.map(g=>g.name+" = "+g.type+", "+list(g.proxies).join(", ")):["DIRECT = select, DIRECT"]),"","[Rule]",...blocked(p).map(d=>"DOMAIN-SUFFIX,"+d+",REJECT"),...rules(p).map(r=>r.type+","+r.value+","+r.action),"FINAL,"+(p.finalPolicy||"DIRECT"),""].join("\n");
}
function exportLoon(p){
  const ps=proxies(p), gs=proxyGroups(p);
  return ["[General]","dns-server = "+servers(p).join(", "),"","[Proxy]",...ps.map(x=>x.name+" = "+x.type+","+x.server+","+x.port+(x.username?","+x.username:"")+(x.password?","+x.password:"")+(x.tls===true?",tls=true":"")+(x.udp===true?",udp=true":"")),"","[Proxy Group]",...(gs.length?gs.map(g=>g.name+" = "+g.type+", "+list(g.proxies).join(", ")):["DIRECT = select, DIRECT"]),"","[Rule]",...blocked(p).map(d=>"DOMAIN-SUFFIX,"+d+",REJECT"),...rules(p).map(r=>r.type+","+r.value+","+r.action),"FINAL,"+(p.finalPolicy||"DIRECT"),""].join("\n");
}
function exportQuantumultX(p){
  const ps=proxies(p), gs=proxyGroups(p);
  return ["[general]","network_check_url = https://www.apple.com/library/test/success.html","","[dns]","server = "+servers(p).join(", "),"","[server_local]",...ps.map(x=>x.type+"="+x.server+":"+x.port+", tag="+x.name+(x.username?", username="+x.username:"")+(x.password?", password="+x.password:"")+(x.tls===true?", over-tls=true":"")),"","[policy]",...(gs.length?gs.map(g=>g.type+" = "+g.name+", "+list(g.proxies).join(", ")):["static = DIRECT"]),"","[filter_local]",...blocked(p).map(d=>"host-suffix,"+d+",reject"),...rules(p).map(r=>"host-suffix,"+r.value+","+(r.action==="REJECT"?"reject":r.action.toLowerCase())),"final,"+String(p.finalPolicy||"DIRECT").toLowerCase(),""].join("\n");
}
export const exportFormats=[
 {id:"surge",label:"Surge",extension:".conf",mime:"text/plain",status:"verified",description:"Surge profile export."},
 {id:"mihomo",label:"Mihomo / Clash-compatible",extension:".yaml",mime:"application/yaml",status:"template-export",description:"YAML target configuration; runtime verification remains separate."},
 {id:"wireguard",label:"WireGuard",extension:".conf",mime:"text/plain",status:"partial-tested",description:"WireGuard configuration; secrets are emitted only when supplied."},
 {id:"shadowrocket",label:"Shadowrocket",extension:".conf",mime:"text/plain",status:"partial-tested",description:"Shadowrocket profile configuration."},
 {id:"loon",label:"Loon",extension:".lcf",mime:"text/plain",status:"template-export",description:"Loon section-based configuration."},
 {id:"stash",label:"Stash",extension:".yaml",mime:"application/yaml",status:"template-export",description:"Stash YAML configuration."},
 {id:"quantumult-x",label:"Quantumult X",extension:".conf",mime:"text/plain",status:"template-export",description:"Quantumult X configuration."},
 {id:"apple-mobileconfig",label:"Apple iOS MobileConfig",extension:".mobileconfig",mime:"application/x-apple-aspen-config",status:"generated",description:"Apple configuration profile."},
 {id:"apple-dns-declaration",label:"Apple Network DNS Settings",extension:".json",mime:"application/json",status:"reference-export",description:"Declarative DNS configuration data."},
 {id:"apple-mobileconfig-legacy",label:"Apple DNSSettings (legacy)",extension:".mobileconfig",mime:"application/x-apple-aspen-config",status:"legacy",description:"Legacy managed DNS payload."}
];

export function getExportArtifact(targetId,input={}){
 const p=policyOf(input);
 switch(targetId){
  case "apple-mobileconfig":
  case "apple-mobileconfig-legacy": return compileAppleMobileConfig(input).content;
  case "apple-dns-declaration": return JSON.stringify(compileAppleDeclarativeDns(input),null,2);
  case "surge": { const surgeInput=input?.policy?input:{policy:p}; const normalized={...surgeInput,policy:{...p,rules:rules(p).map(r=>({type:r.type,value:r.value,policy:r.action}))}}; return compileSurge(normalized).content; }
  case "mihomo": return exportMihomo(p);
  case "wireguard": return exportWireGuard(p);
  case "shadowrocket": return exportShadowrocket(p);
  case "loon": return exportLoon(p);
  case "stash": return exportStash(p);
  case "quantumult-x": return exportQuantumultX(p);
  default: throw new TypeError(`Unsupported export target: ${targetId}`);
 }
}
export function getExportWarnings(targetId,input={}){
 const p=policyOf(input);
 if(targetId==="apple-mobileconfig"||targetId==="apple-mobileconfig-legacy")return compileAppleMobileConfig(input).warnings;
 if(targetId==="wireguard"&&!p.vpn)return [{code:"WIREGUARD_VPN_NOT_ENABLED",message:"WireGuard target selected without VPN enabled."}];
 return [];
}
export function compileTargetExport(targetId,input={}){
 const f=exportFormats.find(x=>x.id===targetId);if(!f)throw new TypeError(`Unsupported export target: ${targetId}`);
 return {targetId,outputFormat:["mihomo","stash"].includes(targetId)?"yaml":["apple-dns-declaration"].includes(targetId)?"json":["apple-mobileconfig","apple-mobileconfig-legacy"].includes(targetId)?"plist":"ini",filename:`${targetId}-config${f.extension}`,mime:f.mime,representation:getExportArtifact(targetId,input),verifiedStatus:f.status,warnings:getExportWarnings(targetId,input)};
}
export {exportMihomo,exportWireGuard,exportShadowrocket,exportLoon,exportStash,exportQuantumultX};
