import * as XLSX from "xlsx";
import { normalizePolicy } from "../../core/src/index.js";
export const EXCEL_SCHEMA_VERSION = "1";
export const SHEETS = Object.freeze({metadata:"Metadata",policy:"Policy",dnsProfiles:"DNS Profiles",dnsServers:"DNS Servers",blocklists:"Blocklists",rules:"Rules",targets:"Targets",webEntry:"Web Entry"});
const text=v=>v==null?"":String(v).trim();
const sheetKey=name=>Object.entries(SHEETS).find(x=>x[1]===name)?.[0]??name;
const FIELDS=[["name","name","string"],["vpn","vpn","boolean"],["dns","dns","boolean"],["routing","routing","boolean"],["blocking.malware","blocking.malware","boolean"],["blocking.trackers","blocking.trackers","boolean"],["dnsProtocol","dnsProtocol","string"],["dnsServerUrl","dnsServerUrl","string"],["dnsServerName","dnsServerName","string"],["dnsAllowFailover","dnsAllowFailover","boolean"],["finalPolicy","finalPolicy","string"],["bypassSystem","bypassSystem","boolean"]];
export class ExcelValidationError extends Error{constructor(code,message,path=""){super(message);this.name="ExcelValidationError";this.code=code;this.path=path;}}
function bool(v,path){if(v===true||v===false)return v;const x=text(v).toLowerCase();if(["1","true","yes"].includes(x))return true;if(["0","false","no"].includes(x))return false;throw new ExcelValidationError("INVALID_BOOLEAN","Expected boolean at "+path+".",path);}
function unique(rows,fields,sheet){const seen=new Map(),errors=[];rows.forEach((r,i)=>{const key=fields.map(f=>text(r[f]).toLowerCase()).join("|");if(!key.replaceAll("|",""))return;if(seen.has(key))errors.push({code:"DUPLICATE",sheet,row:i+2,field:fields.join(","),message:"Duplicate entry; same key already exists at row "+seen.get(key)+"."});else seen.set(key,i+2);});return errors;}
export function validateWorkbookRows(rows={}){const errors=[];if(!(rows.metadata??[]).length)errors.push({code:"SHEET_REQUIRED",sheet:SHEETS.metadata,row:1,field:"",message:"Metadata sheet is required."});errors.push(...unique(rows.dnsProfiles??[],["id"],SHEETS.dnsProfiles),...unique(rows.dnsServers??[],["profile_id","server"],SHEETS.dnsServers),...unique(rows.blocklists??[],["id"],SHEETS.blocklists),...unique(rows.targets??[],["id"],SHEETS.targets));const ids=new Set((rows.dnsProfiles??[]).map(r=>text(r.id)));(rows.dnsServers??[]).forEach((r,i)=>{if(!ids.has(text(r.profile_id)))errors.push({code:"REFERENCE_NOT_FOUND",sheet:SHEETS.dnsServers,row:i+2,field:"profile_id",message:"DNS profile does not exist: "+text(r.profile_id)});});const version=text(rows.metadata?.[0]?.schema_version);if(version&&version!==EXCEL_SCHEMA_VERSION)errors.push({code:"SCHEMA_VERSION_UNSUPPORTED",sheet:SHEETS.metadata,row:2,field:"schema_version",message:"Unsupported Excel schema version: "+version});return{valid:errors.length===0,errors};}
export function policyToWorkbookRows(input){const n=normalizePolicy(input),p=n.policy,metadata=[{schema_version:EXCEL_SCHEMA_VERSION,config_version:n.version,name:p.name??""}],policy=FIELDS.map(([key,field,type])=>{let v=p;for(const part of key.split("."))v=v?.[part];return{field,value:v??"",type};}),profiles=Array.isArray(p.dnsProfiles)?p.dnsProfiles:[],dnsProfiles=profiles.map(x=>({id:x.id,name:x.name,provider:x.provider,address_mode:x.addressMode,protocol:x.protocol,endpoint:x.endpoint,server_name:x.serverName,role:x.role,enabled:x.enabled,order:x.order})),dnsServers=profiles.flatMap(x=>(x.servers??[]).map(server=>({profile_id:x.id,server}))),blocklists=(p.blocklists??[]).map(x=>({id:x.id,provider:x.provider,source:x.source,format:x.format,enabled:x.enabled})),rules=(p.rules??[]).map((x,i)=>({id:x.id??"rule-"+(i+1),json:JSON.stringify(x)})),targets=(p.targets??[]).map((x,i)=>({id:x.id??"target-"+(i+1),json:JSON.stringify(x)})),webEntry=p.webEntry?[{name:p.webEntry.name,url:p.webEntry.url,icon:p.webEntry.icon,enabled:p.webEntry.enabled}]:[];return{metadata,policy,dnsProfiles,dnsServers,blocklists,rules,targets,webEntry};}
export function workbookRowsToPolicy(rows){const check=validateWorkbookRows(rows);if(!check.valid){const e=check.errors[0];throw new ExcelValidationError(e.code,e.message,e.sheet+"!"+(e.field||e.row));}const policy={};for(const row of rows.policy??[]){const field=text(row.field);if(!field)continue;let value=row.value;if(text(row.type)==="boolean")value=bool(value,SHEETS.policy+"."+field);else if(text(row.type)==="string")value=text(value);const parts=field.split(".");if(parts.length===2){policy[parts[0]]??={};policy[parts[0]][parts[1]]=value;}else policy[field]=value;}const profiles=(rows.dnsProfiles??[]).map((r,i)=>({id:text(r.id)||"dns-profile-"+(i+1),name:text(r.name)||"DNS Profile "+(i+1),provider:text(r.provider),addressMode:text(r.address_mode),protocol:text(r.protocol)||"DoH",servers:[],endpoint:text(r.endpoint),serverName:text(r.server_name),role:text(r.role)||"resolver",enabled:r.enabled===""?true:bool(r.enabled,SHEETS.dnsProfiles+".enabled"),order:Number.isFinite(Number(r.order))?Number(r.order):i+1,rules:[]}));const byId=new Map(profiles.map(p=>[p.id,p]));for(const row of rows.dnsServers??[]){const p=byId.get(text(row.profile_id));if(p&&text(row.server))p.servers.push(text(row.server));}policy.dnsProfiles=profiles;policy.blocklists=(rows.blocklists??[]).map(r=>({id:text(r.id),provider:text(r.provider),source:text(r.source),format:text(r.format),enabled:r.enabled===""?true:bool(r.enabled,SHEETS.blocklists+".enabled")}));policy.rules=(rows.rules??[]).map((r,i)=>{try{return JSON.parse(text(r.json));}catch{throw new ExcelValidationError("INVALID_JSON","Invalid JSON in Rules row "+(i+2)+".",SHEETS.rules+".json");}});policy.webEntry=rows.webEntry?.[0]?{name:text(rows.webEntry[0].name),url:text(rows.webEntry[0].url),icon:text(rows.webEntry[0].icon),enabled:rows.webEntry[0].enabled===""?true:bool(rows.webEntry[0].enabled,SHEETS.webEntry+".enabled")}:undefined;return normalizePolicy({version:text(rows.metadata?.[0]?.config_version)||"0.1",policy});}
export function exportWorkbook(input,{type="buffer"}={}){const rows=policyToWorkbookRows(input),wb=XLSX.utils.book_new();for(const [key,name] of Object.entries(SHEETS))XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows[key]??[]),name);return XLSX.write(wb,{bookType:"xlsx",type:type==="base64"?"base64":"buffer"});}
export function importWorkbook(source){const wb=XLSX.read(source,{type:source instanceof Uint8Array||Buffer.isBuffer(source)?"buffer":"base64"}),rows={};for(const name of Object.values(SHEETS)){const ws=wb.Sheets[name];rows[sheetKey(name)]=ws?XLSX.utils.sheet_to_json(ws,{defval:""}):[];}return workbookRowsToPolicy(rows);}
